defaults:
    - data: custom
    - model: no_tex
    - train
    - _self_

n_layers: 2
resume: True
preload: True
log_root: outputs
exp_name: dev 

hydra:
    run:
        dir: ${log_root}/${data.seq}